const phase4 = [
    {
        ratings: [],
        watchlists: [],
        title: "Black Widow",
        summary: "In Marvel Studios' action-packed spy thriller 'Black Widow',  Natasha Romanoff aka Black Widow confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger. ",
        image: "https://resizing.flixster.com/IXEEc62Tz9NIOK0SbouX12vui6g=/68x102/v2/https://resizing.flixster.com/UqanC4hHIFolYIKoZ020-YmubCQ=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzRkMWJjZjI2LWE0MDktNDczZC05ZmNiLTIzMTQ0NTE5MGJiMC5qcGc=",
        releaseDate: "2021-07-09",
        chronologicalOrder: 16,
    },
    {
        ratings: [],
        watchlists: [],
        title: "Shang-Chi and the Legend of the Ten Rings",
        summary: "Shang-Chi and The Legend of The Ten Rings stars Simu Liu as Shang- Chi, who must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.The film also stars Tony Leung as Wenwu, Awkwafina as Shang- Chi's friend Katy and Michelle Yeoh as Jiang Nan, as well as Fala Chen, Meng'er Zhang, Florian Munteanu and Ronny Chieng. ",
        image: "https://resizing.flixster.com/ZkreOI_6pkKjZp9OUEoIG-sBD0M=/68x102/v2/https://resizing.flixster.com/bZGWzjLoyj0GXIQj8vs-8y0xMIA=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzY0NWJhN2RhLTg1Y2YtNDBmYS04YjQ0LWI5MWY4NmIwOGRjMy5qcGc=",
        releaseDate: "2021-09-03",
        chronologicalOrder: 25,
    },
    {
        ratings: [],
        watchlists: [],
        title: "Eternals",
        summary: "Eternals features an exciting new team of Super Heroes in the Marvel Cinematic Universe, ancient aliens who have been living on Earth in secret for thousands of years. Following the events of Avengers: Endgame, an unexpected tragedy forces them out of the shadows to reunite against mankind's most ancient enemy, the Deviants.",
        image: "https://resizing.flixster.com/M5IeuhThKYf2eymGWur_lxRuu1E=/68x102/v2/https://resizing.flixster.com/p8i7HQcy2h8cS_nZhqAq7eU5S6s=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2NjYWQ1NGQ0LTEyMjMtNGFmZi04YjMxLTc0NjQ1Y2VkYzk2MS5qcGc=",
        releaseDate: "2021-11-05",
        chronologicalOrder: 26,
    },
    {
        ratings: [],
        watchlists: [],
        title: "Spider-Man: No Way Home",
        summary: "For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero's identity is revealed, bringing his Super Hero responsibilities into conflict with his normal life and putting those he cares about most at risk. When he enlists Doctor Strange's help to restore his secret, the spell tears a hole in their world, releasing the most powerful villains who've ever fought a Spider-Man in any universe. Now, Peter will have to overcome his greatest challenge yet, which will not only forever alter his own future but the future of the Multiverse.",
        image: "https://resizing.flixster.com/ORTQxtmPArt7uVsDzX5WH5KLOu4=/68x102/v2/https://resizing.flixster.com/8PNiwC2bpe9OecfYZSOVkvYC5vk=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2U5NGM0Y2Q1LTAyYTItNGFjNC1hNWZhLWMzYjJjOTdjMTFhOS5qcGc=",
        releaseDate: "2021-12-17",
        chronologicalOrder: 27,
    },
    {
        ratings: [],
        watchlists: [],
        title: "Doctor Strange in the Multiverse of Madness",
        summary: " The MCU unlocks the Multiverse and pushes its boundaries further than ever before. Journey into the unknown with Doctor Strange, who, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
        image: "https://resizing.flixster.com/-hkyFUfd1de24m5KM7RzJ0sZVPM=/68x102/v2/https://resizing.flixster.com/RfZ4YhxZPdnbMcPd9CkitjdSijQ=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzIxODJmNzBkLWE5MDYtNGYyYi1hZGU4LWMyMTFlMTVjODkzMy5qcGc=",
        releaseDate: "2022-05-06",
        chronologicalOrder: 28,
    },
    {
        ratings: [],
        watchlists: [],
        title: "Thor: Love and Thunder",
        summary: "We find Thor (Chris Hemsworth) on a journey unlike anything he's ever faced -- a quest for inner peace. But his retirement is interrupted by a galactic killer known as Gorr the God Butcher (Christian Bale), who seeks the extinction of the gods. To combat the threat, Thor enlists the help of King Valkyrie (Tessa Thompson), Korg (Taika Waititi) and ex-girlfriend Jane Foster (Natalie Portman), who -- to Thor's surprise -- inexplicably wields his magical hammer, Mjolnir, as the Mighty Thor. Together, they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher's vengeance and stop him before it's too late.",
        image: "https://resizing.flixster.com/ZDjWXINxXWCysWrsuudm4Wukg8s=/68x102/v2/https://resizing.flixster.com/zs8TFWbPfSsndNJWCpNiILwzf3o=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2JiYzJkMmE5LTllZDUtNDQ0Ny1hYmUxLTBmMzk1MDQ4M2NkNC5qcGc=",
        releaseDate: "2022-07-08",
        chronologicalOrder: 29,
    },
    {
        ratings: [],
        watchlists: [],
        title: "Black Panther: Wakanda Forever",
        summary: " Queen Ramonda (Angela Bassett), Shuri (Letitia Wright), M'Baku (Winston Duke), Okoye (Danai Gurira) and the Dora Milaje (including Florence Kasumba) fight to protect their nation from intervening world powers in the wake of King T'Challa's death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia (Lupita Nyong'o) and Everett Ross (Martin Freeman) and forge a new path for the kingdom of Wakanda.",
        image: "https://resizing.flixster.com/99LrDMoB1XYddzApwfJtD7RBmP0=/206x305/v2/https://resizing.flixster.com/QJkeIM6LIvwmRGiLKrNBcpZIk8M=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzAwYzExZjlmLWJlODQtNDY4Mi1iNDhkLWU2YWNmMGIyMDgwMi5qcGc=",
        releaseDate: "2022-11-11",
        chronologicalOrder: 30,
    },
]

module.exports = phase4;