const phase2 = [
  {
    ratings: [],
    watchlists: [],
    title: "Iron Man 3",  
    summary: "Plagued with worry and insomnia since saving New York from destruction, Tony Stark (Robert Downey Jr.), now, is more dependent on the suits that give him his Iron Man persona -- so much so that every aspect of his life is affected, including his relationship with Pepper (Gwyneth Paltrow). After a malevolent enemy known as the Mandarin (Ben Kingsley) reduces his personal world to rubble, Tony must rely solely on instinct and ingenuity to avenge his losses and protect the people he loves.",
    image: "/marvel-images/ironMan3.jpg",
    releaseDate: new Date("2013-05-03"),
    chronologicalOrder: 9,
  },
  {
    ratings: [],
    watchlists: [],
    title: "Thor: The Dark World",
    summary: "In ancient times, the gods of Asgard fought and won a war against an evil race known as the Dark Elves. The survivors were neutralized, and their ultimate weapon -- the Aether -- was buried in a secret location. Hundreds of years later, Jane Foster (Natalie Portman) finds the Aether and becomes its host, forcing Thor (Chris Hemsworth) to bring her to Asgard before Dark Elf Malekith (Christopher Eccleston) captures her and uses the weapon to destroy the Nine Realms -- including Earth.",
    image: "/marvel-images/thorDarkWorld.jpg",
    releaseDate: new Date("2013-11-08"),
    chronologicalOrder: 8,
  },
  {
    ratings: [],
    watchlists: [],
    title: "Captain America: The Winter Soldier",
    summary: "After the cataclysmic events in New York with his fellow Avengers, Steve Rogers, aka Captain America (Chris Evans), lives in the nation's capital as he tries to adjust to modern times. An attack on a S.H.I.E.L.D. colleague throws Rogers into a web of intrigue that places the whole world at risk. Joining forces with the Black Widow (Scarlett Johansson) and a new ally, the Falcon, Rogers struggles to expose an ever-widening conspiracy, but he and his team soon come up against an unexpected enemy.",
    image: "/marvel-images/winterSoldier.jpg",
    releaseDate: new Date("2014-04-04"),
    chronologicalOrder: 10,
  },
  {
    ratings: [],
    watchlists: [],
    title: "Guardians of the Galaxy",
    summary: "Brash space adventurer Peter Quill (Chris Pratt) finds himself the quarry of relentless bounty hunters after he steals an orb coveted by Ronan, a powerful villain. To evade Ronan, Quill is forced into an uneasy truce with four disparate misfits: gun-toting Rocket Raccoon, treelike-humanoid Groot, enigmatic Gamora, and vengeance-driven Drax the Destroyer. But when he discovers the orb's true power and the cosmic threat it poses, Quill must rally his ragtag group to save the universe.",
    image: "/marvel-images/gotg.jpg",
    releaseDate: new Date("2014-08-01"),
    chronologicalOrder: 11,
  },
  {
    ratings: [],
    watchlists: [],
    title: "Avengers: Age of Ultron",
    summary: "When Tony Stark (Robert Downey Jr.) jump-starts a dormant peacekeeping program, things go terribly awry, forcing him, Thor (Chris Hemsworth), the Incredible Hulk (Mark Ruffalo) and the rest of the Avengers to reassemble. As the fate of Earth hangs in the balance, the team is put to the ultimate test as they battle Ultron, a technological terror hell-bent on human extinction. Along the way, they encounter two mysterious and powerful newcomers, Pietro and Wanda Maximoff.",
    image: "/marvel-images/ageOfUltron.jpg",
    releaseDate: new Date("2015-05-01"),
    chronologicalOrder: 13,
  },
  {
    ratings: [],
    watchlists: [],
    title: "Ant-Man",
    summary: "Forced out of his own company by former protégé Darren Cross, Dr. Hank Pym (Michael Douglas) recruits the talents of Scott Lang (Paul Rudd), a master thief just released from prison. Lang becomes Ant-Man, trained by Pym and armed with a suit that allows him to shrink in size, possess superhuman strength and control an army of ants. The miniature hero must use his new skills to prevent Cross, also known as Yellowjacket, from perfecting the same technology and using it as a weapon for evil.",
    image: "/marvel-images/antMan.jpg",
    releaseDate: new Date("2015-07-17"),
    chronologicalOrder: 14,
  },
];

module.exports = phase2;